kind: pipeline
name: default

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
    when:
      event:
        - tag
      branch:
        - master

  - name: build
    image: golang:1.18
    commands:
      - make build-all
    when:
      branch:
        - master
      event:
        - push
        - pull_request
        - tag

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: dist/*
    when:
      event:
        - tag
      branch:
        - master

